### ISSUE TITLE
[Feature Request] Please make column can resize

### ISSUE THREAD

**Issue by idzulfaqor** [Happy-Coding-Clans/vue-easytable#424] opened 2021-12-14 10:16 UTC
### I am opening an issue for
vue-easytable

### Issue Type
Feature

###  Issue Title
Please make column can resize

### What problem does this feature solve?
Please make column width can resize by manually and Ellipsis automatically for long content in a column.

### What does the proposed API look like?
So we can resize column by manually and if content in the column is long, it is can Ellipsis automatically. If user want to see full long content in a column, user can scroll the header column to see the full content. Yap, make it can resize the width of column, and make it Ellipsis automtically when data content in a column have a long text. Thank for make the best table. God bless you

**Comment by huangshuwei** [comment] 2021-12-14 12:54
Thanks for your report. Cell content ellipsis feature is already supported. 

Column width drag is not currently supported. I've put this feature on the todo list:
https://github.com/Happy-Coding-Clans/vue-easytable/projects/3#card-53939414

**Comment by ofthelit** [comment] 2022-02-18 11:00
This is a duplicate of https://github.com/Happy-Coding-Clans/vue-easytable/issues/361

**Comment by huangshuwei** [comment] 2022-10-15 11:31
The new version supports manual column width adjustment：
https://github.com/Happy-Coding-Clans/vue-easytable/releases/tag/v2.21.0

**Closed by huangshuwei** 2022-10-15 11:31 UTC
Labels: 💡 feature
